// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMbJ0nIBjXju8Pf8mXh5_2SRt1PnoAN8',
    appId: '1:219559591313:web:d4528be74e973103fd2e30',
    messagingSenderId: '219559591313',
    projectId: 'gametask-a8eb9',
    authDomain: 'gametask-a8eb9.firebaseapp.com',
    storageBucket: 'gametask-a8eb9.firebasestorage.app',
    measurementId: 'G-7RRF2R3BBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG52TNwnzqncR5lbGvXdLQkBYEE2ExwAk',
    appId: '1:219559591313:android:5d2c9b0a593f5aaffd2e30',
    messagingSenderId: '219559591313',
    projectId: 'gametask-a8eb9',
    storageBucket: 'gametask-a8eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOs71090tDwl64Brofvj7QD9qfgbit6w',
    appId: '1:219559591313:ios:ddb230f5f83e947efd2e30',
    messagingSenderId: '219559591313',
    projectId: 'gametask-a8eb9',
    storageBucket: 'gametask-a8eb9.firebasestorage.app',
    iosBundleId: 'com.example.gameTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOs71090tDwl64Brofvj7QD9qfgbit6w',
    appId: '1:219559591313:ios:ddb230f5f83e947efd2e30',
    messagingSenderId: '219559591313',
    projectId: 'gametask-a8eb9',
    storageBucket: 'gametask-a8eb9.firebasestorage.app',
    iosBundleId: 'com.example.gameTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUMbJ0nIBjXju8Pf8mXh5_2SRt1PnoAN8',
    appId: '1:219559591313:web:7f893cb2053be924fd2e30',
    messagingSenderId: '219559591313',
    projectId: 'gametask-a8eb9',
    authDomain: 'gametask-a8eb9.firebaseapp.com',
    storageBucket: 'gametask-a8eb9.firebasestorage.app',
    measurementId: 'G-YZCGMP6JPB',
  );
}
